version: '3.8'

volumes:
  huggingface-cache:

networks:
  local-stack-network:
    name: local-stack-network
    external: true

services:
  vllm-inference:
    image: vllm/vllm-openai:latest
    command: >
      --model TinyLlama/TinyLlama-1.1B-Chat-v1.0
      --port 8000
      --host 0.0.0.0
      --tensor-parallel-size 1
      --gpu-memory-utilization 0.9
      --max-num-batched-tokens 8192
    networks:
      - local-stack-network
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_HOME=/root/.cache/huggingface
    volumes:
      - huggingface-cache:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3

