version: '3.8'

networks:
  local-stack-network:
    name: local-stack-network
    external: true

services:
  service-mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MLFLOW_SERVER_HOST=0.0.0.0
      - MLFLOW_SERVER_PORT=5000
      - MLFLOW_BACKEND_STORE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@storage-postgres:5432/mlflow
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=s3://mlflow/
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - MLFLOW_S3_ENDPOINT_URL=http://storage-minio:9000
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - local-stack-network
    ports:
      - "5000:5000"
    command: > 
      mlflow server
      --host=0.0.0.0
      --port=5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
